// Default avatar SVG for users without profile pictures
export const DEFAULT_AVATAR = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgdmlld0JveD0iMCAwIDIwMCAyMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxjaXJjbGUgY3g9IjEwMCIgY3k9IjEwMCIgcj0iMTAwIiBmaWxsPSIjMkEyQjU1Ii8+CjxjaXJjbGUgY3g9IjEwMCIgY3k9IjgwIiByPSIzNSIgZmlsbD0iIzU1NTY4QSIvPgo8cGF0aCBkPSJNMTAwIDE0MEMxMjcuNjE0IDE0MCAxNTAgMTU3LjkwOSAxNTAgMTgwVjIwMEg1MFYxODBDNTAgMTU3LjkwOSA3Mi4zODU4IDE0MCAxMDAgMTQwWiIgZmlsbD0iIzU1NTY4QSIvPgo8L3N2Zz4K'

// Helper function to get avatar URL with fallback
export const getAvatarUrl = (profilePic) => {
  return profilePic || DEFAULT_AVATAR
}
